name: Wrangler process automation

on:
  issues:
    types: [opened]

jobs:
  assign_wrangler:
    runs-on: ubuntu-latest
    steps:
    - name: assign wrangler 
      run: |
        echo "CURRENT_WRANGLER=$(gh api repos/openssl/project/issues/402 --jq '.assignees[0].login')" >> $GITHUB_ENV
        echo "Current wrangler is $CURRENT_WRANGLER"
